import Head from 'next/head'

export default function Header() {
  return (
    <>
      <Head>
        <title>Knitto Todos</title>
        <meta name="description" content="Generated by M. Daffa R. A." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
